/* Generated By:JavaCC: Do not edit this line. SMLCConstants.java */
package smlc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SMLCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPAR = 2;
  /** RegularExpression Id. */
  int CPAR = 3;
  /** RegularExpression Id. */
  int SIN = 4;
  /** RegularExpression Id. */
  int COS = 5;
  /** RegularExpression Id. */
  int TAN = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULT = 9;
  /** RegularExpression Id. */
  int DIV = 10;
  /** RegularExpression Id. */
  int POWER = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int DIGITS = 13;
  /** RegularExpression Id. */
  int EOL = 14;
  /** RegularExpression Id. */
  int HELP = 15;
  /** RegularExpression Id. */
  int QUIT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"(\"",
    "\")\"",
    "<SIN>",
    "<COS>",
    "<TAN>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "<NUMBER>",
    "<DIGITS>",
    "<EOL>",
    "\"h\"",
    "<QUIT>",
  };

}
